// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Image : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>CPU architecture</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Architecture { get; set; }
#nullable restore
#else
        public string Architecture { get; set; }
#endif
        /// <summary>image digest</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Digest { get; set; }
#nullable restore
#else
        public string Digest { get; set; }
#endif
        /// <summary>CPU features</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Features { get; set; }
#nullable restore
#else
        public string Features { get; set; }
#endif
        /// <summary>datetime of last pull</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastPulled { get; set; }
#nullable restore
#else
        public string LastPulled { get; set; }
#endif
        /// <summary>datetime of last push</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastPushed { get; set; }
#nullable restore
#else
        public string LastPushed { get; set; }
#endif
        /// <summary>The layers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Docker.Hub.OpenApiClient.Models.Layer>? Layers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Docker.Hub.OpenApiClient.Models.Layer> Layers { get; set; }
#endif
        /// <summary>operating system</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Os { get; set; }
#nullable restore
#else
        public string Os { get; set; }
#endif
        /// <summary>OS features</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OsFeatures { get; set; }
#nullable restore
#else
        public string OsFeatures { get; set; }
#endif
        /// <summary>OS version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OsVersion { get; set; }
#nullable restore
#else
        public string OsVersion { get; set; }
#endif
        /// <summary>size of the image</summary>
        public int? Size { get; set; }
        /// <summary>Status of the image</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ImageStatus? Status { get; set; }
        /// <summary>CPU variant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Variant { get; set; }
#nullable restore
#else
        public string Variant { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.Image"/> and sets the default values.
        /// </summary>
        public Image()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.Image"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Hub.OpenApiClient.Models.Image CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Hub.OpenApiClient.Models.Image();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "architecture", n => { Architecture = n.GetStringValue(); } },
                { "digest", n => { Digest = n.GetStringValue(); } },
                { "features", n => { Features = n.GetStringValue(); } },
                { "last_pulled", n => { LastPulled = n.GetStringValue(); } },
                { "last_pushed", n => { LastPushed = n.GetStringValue(); } },
                { "layers", n => { Layers = n.GetCollectionOfObjectValues<global::Soenneker.Docker.Hub.OpenApiClient.Models.Layer>(global::Soenneker.Docker.Hub.OpenApiClient.Models.Layer.CreateFromDiscriminatorValue)?.AsList(); } },
                { "os", n => { Os = n.GetStringValue(); } },
                { "os_features", n => { OsFeatures = n.GetStringValue(); } },
                { "os_version", n => { OsVersion = n.GetStringValue(); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ImageStatus>(); } },
                { "variant", n => { Variant = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("architecture", Architecture);
            writer.WriteStringValue("digest", Digest);
            writer.WriteStringValue("features", Features);
            writer.WriteStringValue("last_pulled", LastPulled);
            writer.WriteStringValue("last_pushed", LastPushed);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Docker.Hub.OpenApiClient.Models.Layer>("layers", Layers);
            writer.WriteStringValue("os", Os);
            writer.WriteStringValue("os_features", OsFeatures);
            writer.WriteStringValue("os_version", OsVersion);
            writer.WriteIntValue("size", Size);
            writer.WriteEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ImageStatus>("status", Status);
            writer.WriteStringValue("variant", Variant);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
