// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListNamespaceRepositoriesOrderingParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "-name")]
        #pragma warning disable CS1591
        Name1,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_updated")]
        #pragma warning disable CS1591
        LastUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "-last_updated")]
        #pragma warning disable CS1591
        LastUpdated1,
        #pragma warning restore CS1591
        [EnumMember(Value = "pull_count")]
        #pragma warning disable CS1591
        PullCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "-pull_count")]
        #pragma warning disable CS1591
        PullCount1,
        #pragma warning restore CS1591
    }
}
