// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrgAccessTokenResource : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The path of the resource. The format of this will change depending on the type of resource.For TYPE_REPO resources:- Must be an existing repository name (e.g., &quot;myorg/myrepo&quot;)- Can use glob patterns (e.g., &quot;myorg/*&quot; for all repositories in the organization)- Use &quot;*/*/public&quot; to reference all public repositories</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The scopes this token has access to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Scopes { get; set; }
#nullable restore
#else
        public List<string> Scopes { get; set; }
#endif
        /// <summary>The type of resource</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgAccessTokenResourceType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgAccessTokenResource"/> and sets the default values.
        /// </summary>
        public OrgAccessTokenResource()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgAccessTokenResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgAccessTokenResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgAccessTokenResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "path", n => { Path = n.GetStringValue(); } },
                { "scopes", n => { Scopes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgAccessTokenResourceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("path", Path);
            writer.WriteCollectionOfPrimitiveValues<string>("scopes", Scopes);
            writer.WriteEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgAccessTokenResourceType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
