// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    /// <summary>The type of resource</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrgAccessTokenResourceType
    {
        [EnumMember(Value = "TYPE_REPO")]
        #pragma warning disable CS1591
        TypeRepo,
        #pragma warning restore CS1591
        [EnumMember(Value = "TYPE_ORG")]
        #pragma warning disable CS1591
        TypeOrg,
        #pragma warning restore CS1591
    }
}
