// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrgMember : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Company { get; set; }
#nullable restore
#else
        public string Company { get; set; }
#endif
        /// <summary>The date_joined property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateJoined { get; set; }
#nullable restore
#else
        public string DateJoined { get; set; }
#endif
        /// <summary>User&apos;s email address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The full_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullName { get; set; }
#nullable restore
#else
        public string FullName { get; set; }
#endif
        /// <summary>The gravatar_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GravatarEmail { get; set; }
#nullable restore
#else
        public string GravatarEmail { get; set; }
#endif
        /// <summary>The gravatar_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GravatarUrl { get; set; }
#nullable restore
#else
        public string GravatarUrl { get; set; }
#endif
        /// <summary>Groups (Teams) that the user is member of</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Groups { get; set; }
#nullable restore
#else
        public List<string> Groups { get; set; }
#endif
        /// <summary>The UUID trimmed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>If the organization has verified domains, members that have email addresses outside of those domains will be flagged as guests.</summary>
        public bool? IsGuest { get; set; }
        /// <summary>Last desktop version the user used. To access this field, you must have insights visible for your organization. See [Insights](https://docs.docker.com/admin/insights/#view-insights-for-organization-users).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastDesktopVersion { get; set; }
#nullable restore
#else
        public string LastDesktopVersion { get; set; }
#endif
        /// <summary>Last time the user logged in. To access this field, you must have insights visible for your organization. See [Insights](https://docs.docker.com/admin/insights/#view-insights-for-organization-users).</summary>
        public DateTimeOffset? LastLoggedInAt { get; set; }
        /// <summary>Last time the user was seen. To access this field, you must have insights visible for your organization. See [Insights](https://docs.docker.com/admin/insights/#view-insights-for-organization-users).</summary>
        public DateTimeOffset? LastSeenAt { get; set; }
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>The user&apos;s email primary address.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryEmail { get; set; }
#nullable restore
#else
        public string PrimaryEmail { get; set; }
#endif
        /// <summary>The profile_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileUrl { get; set; }
#nullable restore
#else
        public string ProfileUrl { get; set; }
#endif
        /// <summary>The member&apos;s role in the organization (`Owner`, `Editor`,`Member`, or `Invitee` for pending invites).</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMemberRole? Role { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.UserType? Type { get; set; }
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMember"/> and sets the default values.
        /// </summary>
        public OrgMember()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMember"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMember CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMember();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "company", n => { Company = n.GetStringValue(); } },
                { "date_joined", n => { DateJoined = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "full_name", n => { FullName = n.GetStringValue(); } },
                { "gravatar_email", n => { GravatarEmail = n.GetStringValue(); } },
                { "gravatar_url", n => { GravatarUrl = n.GetStringValue(); } },
                { "groups", n => { Groups = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_guest", n => { IsGuest = n.GetBoolValue(); } },
                { "last_desktop_version", n => { LastDesktopVersion = n.GetStringValue(); } },
                { "last_logged_in_at", n => { LastLoggedInAt = n.GetDateTimeOffsetValue(); } },
                { "last_seen_at", n => { LastSeenAt = n.GetDateTimeOffsetValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "primary_email", n => { PrimaryEmail = n.GetStringValue(); } },
                { "profile_url", n => { ProfileUrl = n.GetStringValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMemberRole>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.UserType>(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("company", Company);
            writer.WriteStringValue("date_joined", DateJoined);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("full_name", FullName);
            writer.WriteStringValue("gravatar_email", GravatarEmail);
            writer.WriteStringValue("gravatar_url", GravatarUrl);
            writer.WriteCollectionOfPrimitiveValues<string>("groups", Groups);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_guest", IsGuest);
            writer.WriteStringValue("last_desktop_version", LastDesktopVersion);
            writer.WriteDateTimeOffsetValue("last_logged_in_at", LastLoggedInAt);
            writer.WriteDateTimeOffsetValue("last_seen_at", LastSeenAt);
            writer.WriteStringValue("location", Location);
            writer.WriteStringValue("primary_email", PrimaryEmail);
            writer.WriteStringValue("profile_url", ProfileUrl);
            writer.WriteEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMemberRole>("role", Role);
            writer.WriteEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.UserType>("type", Type);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
