// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    /// <summary>Type of repository</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RepositoryListEntryRepositoryType
    {
        [EnumMember(Value = "image")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "plugin")]
        #pragma warning disable CS1591
        Plugin,
        #pragma warning restore CS1591
    }
}
