// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RepositoryListEntry : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>User&apos;s affiliation with the repository (empty string if no affiliation)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Affiliation { get; set; }
#nullable restore
#else
        public string Affiliation { get; set; }
#endif
        /// <summary>Categories associated with this repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Docker.Hub.OpenApiClient.Models.Category>? Categories { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Docker.Hub.OpenApiClient.Models.Category> Categories { get; set; }
#endif
        /// <summary>Content types supported by this repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ContentTypes { get; set; }
#nullable restore
#else
        public List<string> ContentTypes { get; set; }
#endif
        /// <summary>ISO 8601 timestamp of when the repository was created</summary>
        public DateTimeOffset? DateRegistered { get; set; }
        /// <summary>Repository description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Whether the repository is private</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>ISO 8601 timestamp of when the repository was last modified</summary>
        public DateTimeOffset? LastModified { get; set; }
        /// <summary>ISO 8601 timestamp of when the repository was last updated</summary>
        public DateTimeOffset? LastUpdated { get; set; }
        /// <summary>Media types supported by this repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MediaTypes { get; set; }
#nullable restore
#else
        public List<string> MediaTypes { get; set; }
#endif
        /// <summary>Name of the repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Namespace (organization or username) that owns the repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Namespace { get; set; }
#nullable restore
#else
        public string Namespace { get; set; }
#endif
        /// <summary>Total number of pulls for this repository</summary>
        public int? PullCount { get; set; }
        /// <summary>Type of repository</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntryRepositoryType? RepositoryType { get; set; }
        /// <summary>Number of users who starred this repository</summary>
        public int? StarCount { get; set; }
        /// <summary>Repository status code</summary>
        public int? Status { get; set; }
        /// <summary>Human-readable repository status</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntryStatusDescription? StatusDescription { get; set; }
        /// <summary>Storage size in bytes used by this repository</summary>
        public int? StorageSize { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntry"/> and sets the default values.
        /// </summary>
        public RepositoryListEntry()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntry();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "affiliation", n => { Affiliation = n.GetStringValue(); } },
                { "categories", n => { Categories = n.GetCollectionOfObjectValues<global::Soenneker.Docker.Hub.OpenApiClient.Models.Category>(global::Soenneker.Docker.Hub.OpenApiClient.Models.Category.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content_types", n => { ContentTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "date_registered", n => { DateRegistered = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "is_private", n => { IsPrivate = n.GetBoolValue(); } },
                { "last_modified", n => { LastModified = n.GetDateTimeOffsetValue(); } },
                { "last_updated", n => { LastUpdated = n.GetDateTimeOffsetValue(); } },
                { "media_types", n => { MediaTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "namespace", n => { Namespace = n.GetStringValue(); } },
                { "pull_count", n => { PullCount = n.GetIntValue(); } },
                { "repository_type", n => { RepositoryType = n.GetEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntryRepositoryType>(); } },
                { "star_count", n => { StarCount = n.GetIntValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "status_description", n => { StatusDescription = n.GetEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntryStatusDescription>(); } },
                { "storage_size", n => { StorageSize = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("affiliation", Affiliation);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Docker.Hub.OpenApiClient.Models.Category>("categories", Categories);
            writer.WriteCollectionOfPrimitiveValues<string>("content_types", ContentTypes);
            writer.WriteDateTimeOffsetValue("date_registered", DateRegistered);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("is_private", IsPrivate);
            writer.WriteDateTimeOffsetValue("last_modified", LastModified);
            writer.WriteDateTimeOffsetValue("last_updated", LastUpdated);
            writer.WriteCollectionOfPrimitiveValues<string>("media_types", MediaTypes);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("namespace", Namespace);
            writer.WriteIntValue("pull_count", PullCount);
            writer.WriteEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntryRepositoryType>("repository_type", RepositoryType);
            writer.WriteIntValue("star_count", StarCount);
            writer.WriteIntValue("status", Status);
            writer.WriteEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryListEntryStatusDescription>("status_description", StatusDescription);
            writer.WriteIntValue("storage_size", StorageSize);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
