// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    /// <summary>Human-readable repository status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RepositoryListEntryStatusDescription
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
    }
}
