// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RepositoryInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Repository affiliation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Affiliation { get; set; }
#nullable restore
#else
        public string Affiliation { get; set; }
#endif
        /// <summary>Repository categories</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Docker.Hub.OpenApiClient.Models.Category>? Categories { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Docker.Hub.OpenApiClient.Models.Category> Categories { get; set; }
#endif
        /// <summary>Number of collaborators</summary>
        public long? CollaboratorCount { get; set; }
        /// <summary>Supported content types</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ContentTypes { get; set; }
#nullable restore
#else
        public List<string> ContentTypes { get; set; }
#endif
        /// <summary>ISO 8601 timestamp of when repository was created</summary>
        public DateTimeOffset? DateRegistered { get; set; }
        /// <summary>Short description of the repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Full description of the repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullDescription { get; set; }
#nullable restore
#else
        public string FullDescription { get; set; }
#endif
        /// <summary>Whether the current user has starred this repository</summary>
        public bool? HasStarred { get; set; }
        /// <summary>Hub user information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HubUser { get; set; }
#nullable restore
#else
        public string HubUser { get; set; }
#endif
        /// <summary>The immutable_tags_settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ImmutableTagsSettings? ImmutableTagsSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ImmutableTagsSettings ImmutableTagsSettings { get; set; }
#endif
        /// <summary>Whether the repository has automated builds</summary>
        public bool? IsAutomated { get; set; }
        /// <summary>Whether the repository is private</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>ISO 8601 timestamp of when repository was last modified</summary>
        public DateTimeOffset? LastModified { get; set; }
        /// <summary>ISO 8601 timestamp of when repository was last updated</summary>
        public DateTimeOffset? LastUpdated { get; set; }
        /// <summary>Supported media types</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MediaTypes { get; set; }
#nullable restore
#else
        public List<string> MediaTypes { get; set; }
#endif
        /// <summary>Repository name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Repository namespace</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Namespace { get; set; }
#nullable restore
#else
        public string Namespace { get; set; }
#endif
        /// <summary>The permissions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.RepoPermissions? Permissions { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.RepoPermissions Permissions { get; set; }
#endif
        /// <summary>Number of pulls</summary>
        public long? PullCount { get; set; }
        /// <summary>Type of the repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RepositoryType { get; set; }
#nullable restore
#else
        public string RepositoryType { get; set; }
#endif
        /// <summary>Source of the repository, where it was created from</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>Number of stars</summary>
        public long? StarCount { get; set; }
        /// <summary>Repository status code</summary>
        public int? Status { get; set; }
        /// <summary>Description of the repository status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusDescription { get; set; }
#nullable restore
#else
        public string StatusDescription { get; set; }
#endif
        /// <summary>Storage size in bytes</summary>
        public long? StorageSize { get; set; }
        /// <summary>Username of the repository owner</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryInfo"/> and sets the default values.
        /// </summary>
        public RepositoryInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Hub.OpenApiClient.Models.RepositoryInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "affiliation", n => { Affiliation = n.GetStringValue(); } },
                { "categories", n => { Categories = n.GetCollectionOfObjectValues<global::Soenneker.Docker.Hub.OpenApiClient.Models.Category>(global::Soenneker.Docker.Hub.OpenApiClient.Models.Category.CreateFromDiscriminatorValue)?.AsList(); } },
                { "collaborator_count", n => { CollaboratorCount = n.GetLongValue(); } },
                { "content_types", n => { ContentTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "date_registered", n => { DateRegistered = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "full_description", n => { FullDescription = n.GetStringValue(); } },
                { "has_starred", n => { HasStarred = n.GetBoolValue(); } },
                { "hub_user", n => { HubUser = n.GetStringValue(); } },
                { "immutable_tags_settings", n => { ImmutableTagsSettings = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ImmutableTagsSettings>(global::Soenneker.Docker.Hub.OpenApiClient.Models.ImmutableTagsSettings.CreateFromDiscriminatorValue); } },
                { "is_automated", n => { IsAutomated = n.GetBoolValue(); } },
                { "is_private", n => { IsPrivate = n.GetBoolValue(); } },
                { "last_modified", n => { LastModified = n.GetDateTimeOffsetValue(); } },
                { "last_updated", n => { LastUpdated = n.GetDateTimeOffsetValue(); } },
                { "media_types", n => { MediaTypes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "namespace", n => { Namespace = n.GetStringValue(); } },
                { "permissions", n => { Permissions = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.RepoPermissions>(global::Soenneker.Docker.Hub.OpenApiClient.Models.RepoPermissions.CreateFromDiscriminatorValue); } },
                { "pull_count", n => { PullCount = n.GetLongValue(); } },
                { "repository_type", n => { RepositoryType = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "star_count", n => { StarCount = n.GetLongValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "status_description", n => { StatusDescription = n.GetStringValue(); } },
                { "storage_size", n => { StorageSize = n.GetLongValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("affiliation", Affiliation);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Docker.Hub.OpenApiClient.Models.Category>("categories", Categories);
            writer.WriteLongValue("collaborator_count", CollaboratorCount);
            writer.WriteCollectionOfPrimitiveValues<string>("content_types", ContentTypes);
            writer.WriteDateTimeOffsetValue("date_registered", DateRegistered);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("full_description", FullDescription);
            writer.WriteBoolValue("has_starred", HasStarred);
            writer.WriteStringValue("hub_user", HubUser);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ImmutableTagsSettings>("immutable_tags_settings", ImmutableTagsSettings);
            writer.WriteBoolValue("is_automated", IsAutomated);
            writer.WriteBoolValue("is_private", IsPrivate);
            writer.WriteDateTimeOffsetValue("last_modified", LastModified);
            writer.WriteDateTimeOffsetValue("last_updated", LastUpdated);
            writer.WriteCollectionOfPrimitiveValues<string>("media_types", MediaTypes);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("namespace", Namespace);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.RepoPermissions>("permissions", Permissions);
            writer.WriteLongValue("pull_count", PullCount);
            writer.WriteStringValue("repository_type", RepositoryType);
            writer.WriteStringValue("source", Source);
            writer.WriteLongValue("star_count", StarCount);
            writer.WriteIntValue("status", Status);
            writer.WriteStringValue("status_description", StatusDescription);
            writer.WriteLongValue("storage_size", StorageSize);
            writer.WriteStringValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
