// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScimSchemaAttribute : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The caseExact property</summary>
        public bool? CaseExact { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The multiValued property</summary>
        public bool? MultiValued { get; set; }
        /// <summary>The mutability property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mutability { get; set; }
#nullable restore
#else
        public string Mutability { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The required property</summary>
        public bool? Required { get; set; }
        /// <summary>The returned property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Returned { get; set; }
#nullable restore
#else
        public string Returned { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimSchemaAttributeType? Type { get; set; }
        /// <summary>The uniqueness property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uniqueness { get; set; }
#nullable restore
#else
        public string Uniqueness { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimSchemaAttribute"/> and sets the default values.
        /// </summary>
        public ScimSchemaAttribute()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimSchemaAttribute"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimSchemaAttribute CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimSchemaAttribute();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "caseExact", n => { CaseExact = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "multiValued", n => { MultiValued = n.GetBoolValue(); } },
                { "mutability", n => { Mutability = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "returned", n => { Returned = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimSchemaAttributeType>(); } },
                { "uniqueness", n => { Uniqueness = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("caseExact", CaseExact);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("multiValued", MultiValued);
            writer.WriteStringValue("mutability", Mutability);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("required", Required);
            writer.WriteStringValue("returned", Returned);
            writer.WriteEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimSchemaAttributeType>("type", Type);
            writer.WriteStringValue("uniqueness", Uniqueness);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
