// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScimServiceProviderConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authenticationSchemes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigAuthenticationSchemes? AuthenticationSchemes { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigAuthenticationSchemes AuthenticationSchemes { get; set; }
#endif
        /// <summary>The bulk property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigBulk? Bulk { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigBulk Bulk { get; set; }
#endif
        /// <summary>The changePassword property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigChangePassword? ChangePassword { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigChangePassword ChangePassword { get; set; }
#endif
        /// <summary>The documentationUri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentationUri { get; set; }
#nullable restore
#else
        public string DocumentationUri { get; set; }
#endif
        /// <summary>The etag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigEtag? Etag { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigEtag Etag { get; set; }
#endif
        /// <summary>The filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigFilter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigFilter Filter { get; set; }
#endif
        /// <summary>The patch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigPatch? Patch { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigPatch Patch { get; set; }
#endif
        /// <summary>The schemas property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Schemas { get; set; }
#nullable restore
#else
        public List<string> Schemas { get; set; }
#endif
        /// <summary>The sort property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigSort? Sort { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigSort Sort { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfig"/> and sets the default values.
        /// </summary>
        public ScimServiceProviderConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authenticationSchemes", n => { AuthenticationSchemes = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigAuthenticationSchemes>(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigAuthenticationSchemes.CreateFromDiscriminatorValue); } },
                { "bulk", n => { Bulk = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigBulk>(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigBulk.CreateFromDiscriminatorValue); } },
                { "changePassword", n => { ChangePassword = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigChangePassword>(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigChangePassword.CreateFromDiscriminatorValue); } },
                { "documentationUri", n => { DocumentationUri = n.GetStringValue(); } },
                { "etag", n => { Etag = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigEtag>(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigEtag.CreateFromDiscriminatorValue); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigFilter>(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigFilter.CreateFromDiscriminatorValue); } },
                { "patch", n => { Patch = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigPatch>(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigPatch.CreateFromDiscriminatorValue); } },
                { "schemas", n => { Schemas = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sort", n => { Sort = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigSort>(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigSort.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigAuthenticationSchemes>("authenticationSchemes", AuthenticationSchemes);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigBulk>("bulk", Bulk);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigChangePassword>("changePassword", ChangePassword);
            writer.WriteStringValue("documentationUri", DocumentationUri);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigEtag>("etag", Etag);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigFilter>("filter", Filter);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigPatch>("patch", Patch);
            writer.WriteCollectionOfPrimitiveValues<string>("schemas", Schemas);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimServiceProviderConfigSort>("sort", Sort);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
