// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Tag : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of the user that pushed the tag</summary>
        public int? Creator { get; set; }
        /// <summary>compressed size (sum of all layers) of the tagged image</summary>
        public int? FullSize { get; set; }
        /// <summary>tag ID</summary>
        public int? Id { get; set; }
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.Image? Images { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.Image Images { get; set; }
#endif
        /// <summary>datetime of last update</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdated { get; set; }
#nullable restore
#else
        public string LastUpdated { get; set; }
#endif
        /// <summary>ID of the last user that updated the tag</summary>
        public int? LastUpdater { get; set; }
        /// <summary>Hub username of the user that updated the tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUpdaterUsername { get; set; }
#nullable restore
#else
        public string LastUpdaterUsername { get; set; }
#endif
        /// <summary>name of the tag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>repository ID</summary>
        public int? Repository { get; set; }
        /// <summary>whether a tag has been pushed to or pulled in the past month</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.Models.TagStatus? Status { get; set; }
        /// <summary>datetime of last pull</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TagLastPulled { get; set; }
#nullable restore
#else
        public string TagLastPulled { get; set; }
#endif
        /// <summary>datetime of last push</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TagLastPushed { get; set; }
#nullable restore
#else
        public string TagLastPushed { get; set; }
#endif
        /// <summary>repository API version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? V2 { get; set; }
#nullable restore
#else
        public string V2 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.Tag"/> and sets the default values.
        /// </summary>
        public Tag()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.Tag"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Hub.OpenApiClient.Models.Tag CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Hub.OpenApiClient.Models.Tag();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creator", n => { Creator = n.GetIntValue(); } },
                { "full_size", n => { FullSize = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "images", n => { Images = n.GetObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.Image>(global::Soenneker.Docker.Hub.OpenApiClient.Models.Image.CreateFromDiscriminatorValue); } },
                { "last_updated", n => { LastUpdated = n.GetStringValue(); } },
                { "last_updater", n => { LastUpdater = n.GetIntValue(); } },
                { "last_updater_username", n => { LastUpdaterUsername = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "repository", n => { Repository = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.TagStatus>(); } },
                { "tag_last_pulled", n => { TagLastPulled = n.GetStringValue(); } },
                { "tag_last_pushed", n => { TagLastPushed = n.GetStringValue(); } },
                { "v2", n => { V2 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("creator", Creator);
            writer.WriteIntValue("full_size", FullSize);
            writer.WriteIntValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.Image>("images", Images);
            writer.WriteStringValue("last_updated", LastUpdated);
            writer.WriteIntValue("last_updater", LastUpdater);
            writer.WriteStringValue("last_updater_username", LastUpdaterUsername);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("repository", Repository);
            writer.WriteEnumValue<global::Soenneker.Docker.Hub.OpenApiClient.Models.TagStatus>("status", Status);
            writer.WriteStringValue("tag_last_pulled", TagLastPulled);
            writer.WriteStringValue("tag_last_pushed", TagLastPushed);
            writer.WriteStringValue("v2", V2);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
