// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "User")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "Org")]
        #pragma warning disable CS1591
        Org,
        #pragma warning restore CS1591
    }
}
