// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\users\login
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoginRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login.LoginRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoginRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users/login", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login.LoginRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoginRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users/login", rawUrl)
        {
        }
        /// <summary>
        /// Creates and returns a bearer token in JWT format that you can use to authenticate with Docker Hub APIs.The returned token is used in the HTTP Authorization header like `Authorization: Bearer {TOKEN}`._**As of September 16, 2024, this route requires a personal access token (PAT) instead of a password if your organization has SSO enforced.**_&lt;div style=&quot;background-color:rgb(255, 165, 0, .25); padding:5px; border-radius:4px&quot;&gt;  &lt;strong&gt;Deprecated&lt;/strong&gt;: Use [&lt;a href=&quot;#tag/authentication-api/operation/AuthCreateAccessToken&quot;&gt;Create access token&lt;/a&gt;] instead.&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse"/></returns>
        /// <param name="body">User login details</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginErrorResponse">When receiving a 401 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse?> PostAsync(global::Soenneker.Docker.Hub.OpenApiClient.Models.UsersLoginRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse> PostAsync(global::Soenneker.Docker.Hub.OpenApiClient.Models.UsersLoginRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse>(requestInfo, global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates and returns a bearer token in JWT format that you can use to authenticate with Docker Hub APIs.The returned token is used in the HTTP Authorization header like `Authorization: Bearer {TOKEN}`._**As of September 16, 2024, this route requires a personal access token (PAT) instead of a password if your organization has SSO enforced.**_&lt;div style=&quot;background-color:rgb(255, 165, 0, .25); padding:5px; border-radius:4px&quot;&gt;  &lt;strong&gt;Deprecated&lt;/strong&gt;: Use [&lt;a href=&quot;#tag/authentication-api/operation/AuthCreateAccessToken&quot;&gt;Create access token&lt;/a&gt;] instead.&lt;/div&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">User login details</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Docker.Hub.OpenApiClient.Models.UsersLoginRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Docker.Hub.OpenApiClient.Models.UsersLoginRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login.LoginRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login.LoginRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login.LoginRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
