// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.Models;
using Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.Actions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\auditlogs\{account}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAccountItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The actions property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.Actions.ActionsRequestBuilder Actions
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/auditlogs/{account}{?action*,actor*,from*,name*,page*,page_size*,to*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/auditlogs/{account}{?action*,actor*,from*,name*,page*,page_size*,to*}", rawUrl)
        {
        }
        /// <summary>
        /// List audit log events for a given namespace.&lt;span class=&quot;oat&quot;&gt;&lt;/span&gt;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.GetAuditLogsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.AuditLogsListAuditLogs429ResponseSchema">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.AuditLogsListAuditLogs500ResponseSchema">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.RpcStatus">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.GetAuditLogsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder.WithAccountItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.GetAuditLogsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder.WithAccountItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "429", global::Soenneker.Docker.Hub.OpenApiClient.Models.AuditLogsListAuditLogs429ResponseSchema.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Docker.Hub.OpenApiClient.Models.AuditLogsListAuditLogs500ResponseSchema.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Docker.Hub.OpenApiClient.Models.RpcStatus.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Docker.Hub.OpenApiClient.Models.GetAuditLogsResponse>(requestInfo, global::Soenneker.Docker.Hub.OpenApiClient.Models.GetAuditLogsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List audit log events for a given namespace.&lt;span class=&quot;oat&quot;&gt;&lt;/span&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder.WithAccountItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder.WithAccountItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.Item.WithAccountItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List audit log events for a given namespace.&lt;span class=&quot;oat&quot;&gt;&lt;/span&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithAccountItemRequestBuilderGetQueryParameters 
        {
            /// <summary>action name one of [&quot;repo.tag.push&quot;, ...]. Optional parameter to filter specific audit log actions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("action")]
            public string? Action { get; set; }
#nullable restore
#else
            [QueryParameter("action")]
            public string Action { get; set; }
#endif
            /// <summary>actor name. Optional parameter to filter audit log events to the specific user who triggered the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("actor")]
            public string? Actor { get; set; }
#nullable restore
#else
            [QueryParameter("actor")]
            public string Actor { get; set; }
#endif
            /// <summary>Start of the time window you wish to query audit events for.</summary>
            [QueryParameter("from")]
            public DateTimeOffset? From { get; set; }
            /// <summary>name. Optional parameter to filter audit log events to a specific name. For repository events, this is the name of the repository. For organization events, this is the name of the organization. For team member events, this is the username of the team member.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>page - specify page number. Page number to get.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>page_size - specify page size. Number of events to return per page.</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>End of the time window you wish to query audit events for.</summary>
            [QueryParameter("to")]
            public DateTimeOffset? To { get; set; }
        }
    }
}
#pragma warning restore CS0618
