// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login;
using Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login.LoginRequestBuilder Login
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The TwofaLogin property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin.TwofaLoginRequestBuilder TwofaLogin
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin.TwofaLoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
