// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.ResourceTypes;
using Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Schemas;
using Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.ServiceProviderConfig;
using Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\scim\2.0
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TwoZeroRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ResourceTypes property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.ResourceTypes.ResourceTypesRequestBuilder ResourceTypes
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.ResourceTypes.ResourceTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Schemas property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Schemas.SchemasRequestBuilder Schemas
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Schemas.SchemasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ServiceProviderConfig property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.ServiceProviderConfig.ServiceProviderConfigRequestBuilder ServiceProviderConfig
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.ServiceProviderConfig.ServiceProviderConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Users property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.TwoZeroRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TwoZeroRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/scim/2.0", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.TwoZeroRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TwoZeroRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/scim/2.0", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
