// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.AccessTokens;
using Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Groups;
using Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Invites;
using Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members;
using Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Settings;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\orgs\{name-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accessTokens property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.AccessTokens.AccessTokensRequestBuilder AccessTokens
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.AccessTokens.AccessTokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Groups.GroupsRequestBuilder Groups
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invites property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Invites.InvitesRequestBuilder Invites
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Invites.InvitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The members property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder Members
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.NameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/orgs/{name%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.NameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/orgs/{name%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
