// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Scim
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\scim
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScimRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The TwoZero property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.TwoZeroRequestBuilder TwoZero
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.TwoZeroRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.ScimRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScimRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/scim", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.ScimRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScimRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/scim", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
