// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.V2.AccessTokens;
using Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs;
using Soenneker.Docker.Hub.OpenApiClient.V2.Auth;
using Soenneker.Docker.Hub.OpenApiClient.V2.Invites;
using Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces;
using Soenneker.Docker.Hub.OpenApiClient.V2.Orgs;
using Soenneker.Docker.Hub.OpenApiClient.V2.Repositories;
using Soenneker.Docker.Hub.OpenApiClient.V2.Scim;
using Soenneker.Docker.Hub.OpenApiClient.V2.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accessTokens property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.AccessTokens.AccessTokensRequestBuilder AccessTokens
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.AccessTokens.AccessTokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auditlogs property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.AuditlogsRequestBuilder Auditlogs
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Auditlogs.AuditlogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Auth.AuthRequestBuilder Auth
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invites property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Invites.InvitesRequestBuilder Invites
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Invites.InvitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The namespaces property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces.NamespacesRequestBuilder Namespaces
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces.NamespacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgs property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.OrgsRequestBuilder Orgs
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.OrgsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repositories property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Repositories.RepositoriesRequestBuilder Repositories
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Repositories.RepositoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scim property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.ScimRequestBuilder Scim
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.ScimRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
