// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\scim\2.0\Users\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item.UsersItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/scim/2.0/Users/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item.UsersItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/scim/2.0/Users/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a user by ID.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimBadRequestResponseScimJson">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUnauthorizedResponseScimJson">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimForbiddenResponseScimJson">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimNotFoundResponseScimJson">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimErrorResponseScimJson">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimBadRequestResponseScimJson.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUnauthorizedResponseScimJson.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimForbiddenResponseScimJson.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimNotFoundResponseScimJson.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimErrorResponseScimJson.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser>(requestInfo, global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates a user. This route is used to change the user&apos;s name, activate, and deactivate the user.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimBadRequestResponseScimJson">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUnauthorizedResponseScimJson">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimForbiddenResponseScimJson">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimNotFoundResponseScimJson">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimConflictResponseScimJson">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimErrorResponseScimJson">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser?> PutAsync(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUpdateUserRequestRequestScimJson body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser> PutAsync(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUpdateUserRequestRequestScimJson body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimBadRequestResponseScimJson.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUnauthorizedResponseScimJson.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimForbiddenResponseScimJson.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimNotFoundResponseScimJson.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimConflictResponseScimJson.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimErrorResponseScimJson.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser>(requestInfo, global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a user by ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/scim+json");
            return requestInfo;
        }
        /// <summary>
        /// Updates a user. This route is used to change the user&apos;s name, activate, and deactivate the user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUpdateUserRequestRequestScimJson body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUpdateUserRequestRequestScimJson body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/scim+json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/scim+json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item.UsersItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item.UsersItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item.UsersItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
