// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\users\2fa-login
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TwofaLoginRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin.TwofaLoginRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TwofaLoginRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users/2fa-login", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin.TwofaLoginRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TwofaLoginRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/users/2fa-login", rawUrl)
        {
        }
        /// <summary>
        /// When a user has two-factor authentication (2FA) enabled, this is the second call to perform after `/v2/users/login` call.Creates and returns a bearer token in JWT format that you can use to authenticate with Docker Hub APIs.The returned token is used in the HTTP Authorization header like `Authorization: Bearer {TOKEN}`.Most Docker Hub APIs require this token either to consume or to get detailed information. For example, to list images in a private repository.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse"/></returns>
        /// <param name="body">Second factor user login details</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsers2FaLoginErrorResponse">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse?> PostAsync(global::Soenneker.Docker.Hub.OpenApiClient.Models.Users2FaLoginRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse> PostAsync(global::Soenneker.Docker.Hub.OpenApiClient.Models.Users2FaLoginRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsers2FaLoginErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse>(requestInfo, global::Soenneker.Docker.Hub.OpenApiClient.Models.PostUsersLoginSuccessResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// When a user has two-factor authentication (2FA) enabled, this is the second call to perform after `/v2/users/login` call.Creates and returns a bearer token in JWT format that you can use to authenticate with Docker Hub APIs.The returned token is used in the HTTP Authorization header like `Authorization: Bearer {TOKEN}`.Most Docker Hub APIs require this token either to consume or to get detailed information. For example, to list images in a private repository.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Second factor user login details</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Docker.Hub.OpenApiClient.Models.Users2FaLoginRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Docker.Hub.OpenApiClient.Models.Users2FaLoginRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin.TwofaLoginRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin.TwofaLoginRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Docker.Hub.OpenApiClient.V2.Users.TwofaLogin.TwofaLoginRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
