// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.Models;
using Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\scim\2.0\Users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Docker.Hub.OpenApiClient.v2.scim.TwoZero.Users.item collection</summary>
        /// <param name="position">The user ID.</param>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item.UsersItemRequestBuilder"/></returns>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item.UsersItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.Item.UsersItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/scim/2.0/Users{?attributes*,count*,filter*,sortBy*,sortOrder*,startIndex*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/scim/2.0/Users{?attributes*,count*,filter*,sortBy*,sortOrder*,startIndex*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns paginated users for an organization. Use `startIndex` and `count` query parameters to receive paginated results.**Sorting:**Sorting allows you to specify the order in which resources are returned by specifying a combination of `sortBy` and `sortOrder` query parameters.The `sortBy` parameter specifies the attribute whose value will be used to order the returned responses. The `sortOrder` parameter defines the order in which the `sortBy` parameter is applied. Allowed values are &quot;ascending&quot; and &quot;descending&quot;.**Filtering:**You can request a subset of resources by specifying the `filter` query parameter containing a filter expression. Attribute names and attribute operators used in filters are case insensitive. The filter parameter must contain at least one valid expression. Each expression must contain an attribute name followed by an attribute operator and an optional value.Supported operators are listed below.- `eq` equal- `ne` not equal- `co` contains- `sw` starts with- `and` Logical &quot;and&quot;- `or` Logical &quot;or&quot;- `not` &quot;Not&quot; function- `()` Precedence grouping
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimGetUsersRespResponseScimJson"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimBadRequestResponseScimJson">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUnauthorizedResponseScimJson">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimForbiddenResponseScimJson">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimNotFoundResponseScimJson">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimErrorResponseScimJson">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimGetUsersRespResponseScimJson?> GetAsync(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimGetUsersRespResponseScimJson> GetAsync(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimBadRequestResponseScimJson.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUnauthorizedResponseScimJson.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimForbiddenResponseScimJson.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimNotFoundResponseScimJson.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimErrorResponseScimJson.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimGetUsersRespResponseScimJson>(requestInfo, global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimGetUsersRespResponseScimJson.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a user. If the user already exists by email, they are assigned to the organization on the &quot;company&quot; team.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimBadRequestResponseScimJson">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUnauthorizedResponseScimJson">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimForbiddenResponseScimJson">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimNotFoundResponseScimJson">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimConflictResponseScimJson">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimErrorResponseScimJson">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser?> PostAsync(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimCreateUserRequestRequestScimJson body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser> PostAsync(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimCreateUserRequestRequestScimJson body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimBadRequestResponseScimJson.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUnauthorizedResponseScimJson.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimForbiddenResponseScimJson.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimNotFoundResponseScimJson.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimConflictResponseScimJson.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimErrorResponseScimJson.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser>(requestInfo, global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimUser.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns paginated users for an organization. Use `startIndex` and `count` query parameters to receive paginated results.**Sorting:**Sorting allows you to specify the order in which resources are returned by specifying a combination of `sortBy` and `sortOrder` query parameters.The `sortBy` parameter specifies the attribute whose value will be used to order the returned responses. The `sortOrder` parameter defines the order in which the `sortBy` parameter is applied. Allowed values are &quot;ascending&quot; and &quot;descending&quot;.**Filtering:**You can request a subset of resources by specifying the `filter` query parameter containing a filter expression. Attribute names and attribute operators used in filters are case insensitive. The filter parameter must contain at least one valid expression. Each expression must contain an attribute name followed by an attribute operator and an optional value.Supported operators are listed below.- `eq` equal- `ne` not equal- `co` contains- `sw` starts with- `and` Logical &quot;and&quot;- `or` Logical &quot;or&quot;- `not` &quot;Not&quot; function- `()` Precedence grouping
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder.UsersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/scim+json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a user. If the user already exists by email, they are assigned to the organization on the &quot;company&quot; team.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimCreateUserRequestRequestScimJson body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Docker.Hub.OpenApiClient.Models.ScimCreateUserRequestRequestScimJson body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/scim+json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/scim+json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Docker.Hub.OpenApiClient.V2.Scim.TwoZero.Users.UsersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns paginated users for an organization. Use `startIndex` and `count` query parameters to receive paginated results.**Sorting:**Sorting allows you to specify the order in which resources are returned by specifying a combination of `sortBy` and `sortOrder` query parameters.The `sortBy` parameter specifies the attribute whose value will be used to order the returned responses. The `sortOrder` parameter defines the order in which the `sortBy` parameter is applied. Allowed values are &quot;ascending&quot; and &quot;descending&quot;.**Filtering:**You can request a subset of resources by specifying the `filter` query parameter containing a filter expression. Attribute names and attribute operators used in filters are case insensitive. The filter parameter must contain at least one valid expression. Each expression must contain an attribute name followed by an attribute operator and an optional value.Supported operators are listed below.- `eq` equal- `ne` not equal- `co` contains- `sw` starts with- `and` Logical &quot;and&quot;- `or` Logical &quot;or&quot;- `not` &quot;Not&quot; function- `()` Precedence grouping
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UsersRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma delimited list of attributes to limit to in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("attributes")]
            public string? Attributes { get; set; }
#nullable restore
#else
            [QueryParameter("attributes")]
            public string Attributes { get; set; }
#endif
            #pragma warning disable CS1591
            [QueryParameter("count")]
            public int? Count { get; set; }
            #pragma warning restore CS1591
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("filter")]
            public string? Filter { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("filter")]
            public string Filter { get; set; }
            #pragma warning restore CS1591
#endif
            /// <summary>User attribute to sort by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sortBy")]
            public string? SortBy { get; set; }
#nullable restore
#else
            [QueryParameter("sortBy")]
            public string SortBy { get; set; }
#endif
            #pragma warning disable CS1591
            [QueryParameter("sortOrder")]
            public global::Soenneker.Docker.Hub.OpenApiClient.Models.GetV2Scim20UsersSortOrderParameter? SortOrder { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("startIndex")]
            public int? StartIndex { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
