// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.Models;
using Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.Export;
using Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\orgs\{name-id}\members
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MembersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The export property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.Export.ExportRequestBuilder Export
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Docker.Hub.OpenApiClient.v2.orgs.item.members.item collection</summary>
        /// <param name="position">Username, identifier for the user (namespace, DockerID).</param>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.Item.WithUsernameItemRequestBuilder"/></returns>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.Item.WithUsernameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("username", position);
                return new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.Item.WithUsernameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/orgs/{name%2Did}/members{?invites*,page*,page_size*,role*,search*,type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/orgs/{name%2Did}/members{?invites*,page*,page_size*,role*,search*,type*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of members for an organization._The following fields are only visible to orgs with insights enabled._- `last_logged_in_at`- `last_seen_at`- `last_desktop_version`To make visible, please see [View Insights for organization users](https://docs.docker.com/admin/insights/#view-insights-for-organization-users).&lt;span class=&quot;oat&quot;&gt;&lt;/span&gt;
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMemberPaginated&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.Error2">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.Error2">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.Error2">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Docker.Hub.OpenApiClient.Models.Error2">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMemberPaginated>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder.MembersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMemberPaginated>> GetAsync(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder.MembersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Docker.Hub.OpenApiClient.Models.Error2.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Docker.Hub.OpenApiClient.Models.Error2.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Docker.Hub.OpenApiClient.Models.Error2.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Docker.Hub.OpenApiClient.Models.Error2.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMemberPaginated>(requestInfo, global::Soenneker.Docker.Hub.OpenApiClient.Models.OrgMemberPaginated.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns a list of members for an organization._The following fields are only visible to orgs with insights enabled._- `last_logged_in_at`- `last_seen_at`- `last_desktop_version`To make visible, please see [View Insights for organization users](https://docs.docker.com/admin/insights/#view-insights-for-organization-users).&lt;span class=&quot;oat&quot;&gt;&lt;/span&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder.MembersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder.MembersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Docker.Hub.OpenApiClient.V2.Orgs.Item.Members.MembersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of members for an organization._The following fields are only visible to orgs with insights enabled._- `last_logged_in_at`- `last_seen_at`- `last_desktop_version`To make visible, please see [View Insights for organization users](https://docs.docker.com/admin/insights/#view-insights-for-organization-users).&lt;span class=&quot;oat&quot;&gt;&lt;/span&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MembersRequestBuilderGetQueryParameters 
        {
            /// <summary>Include invites in the response.</summary>
            [QueryParameter("invites")]
            public bool? Invites { get; set; }
            /// <summary>Page number (starts on 1).</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Number of items (rows) per page.</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            #pragma warning disable CS1591
            [QueryParameter("role")]
            public global::Soenneker.Docker.Hub.OpenApiClient.Models.Role? Role { get; set; }
            #pragma warning restore CS1591
            /// <summary>Search term.</summary>
            [QueryParameter("search")]
            public int? Search { get; set; }
            #pragma warning disable CS1591
            [QueryParameter("type")]
            public global::Soenneker.Docker.Hub.OpenApiClient.Models.TypeValue? Type { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
