// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.V2.Repositories.Item.Item.Groups;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Repositories.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\repositories\{namespaceValue}\{repository}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRepositoryItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The groups property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Repositories.Item.Item.Groups.GroupsRequestBuilder Groups
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Repositories.Item.Item.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Repositories.Item.Item.WithRepositoryItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRepositoryItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/repositories/{namespaceValue}/{repository}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Repositories.Item.Item.WithRepositoryItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRepositoryItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/repositories/{namespaceValue}/{repository}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
