// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces.Item.Repositories;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\namespaces\{namespaceValue}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithNamespaceValueItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The repositories property</summary>
        public global::Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces.Item.Repositories.RepositoriesRequestBuilder Repositories
        {
            get => new global::Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces.Item.Repositories.RepositoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces.Item.WithNamespaceValueItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithNamespaceValueItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/namespaces/{namespaceValue}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Hub.OpenApiClient.V2.Namespaces.Item.WithNamespaceValueItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithNamespaceValueItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/namespaces/{namespaceValue}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
